#!/bin/bash

# Install Google ADK
python -m venv ~/.venv
source ~/.venv/bin/activate
pip install google-adk &> /tmp/adk.log
if ! grep -q "source ~/.venv/bin/activate" ~/.bashrc; then
  printf 'if [ -f ~/.venv/bin/activate ]; then\n  source ~/.venv/bin/activate\nfi\n' >> ~/.bashrc
fi

# Install Gemini CLI
sudo npm install -g @google/gemini-cli &> /tmp/gemini.log
